version: "3.1"

services:
  server:
    build:
      context: .
    ports:
      - "2121:8080"
    environment:
      - "PORT=8080"
    volumes:
      - ./ignore/files:/files
      - ./ignore/auth.yml:/auth.yml
