---
apiVersion: v1
kind: Namespace
metadata:
  name: file-server
---
apiVersion: v1
kind: Service
metadata:
  name: file-server
  namespace: file-server
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: file-server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /storage/files
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
  namespace: file-server
  labels:
    app: file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      restartPolicy: Always
      containers:
        - name: server
          image: kamackay/file-server:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          volumeMounts:
            - name: file-volume
              mountPath: /files
      volumes:
        - name: file-volume
          hostPath:
              path: "/storage/files"
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: file-server-mapping
  namespace: file-server
spec:
  prefix: /files/
  rewrite: /
  service: file-server.file-server:8080
---
