---
apiVersion: v1
kind: Service
metadata:
  name: file-server
  namespace: file-server
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    service: file-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: file-server
  namespace: file-server
spec:
  serviceName: file-server
  selector:
    matchLabels:
      service: file-server
  template:
    metadata:
      labels:
        service: file-server
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      containers:
        - name: server
          image: registry.gitlab.com/kamackay/filer:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
          env:
            - name: PORT
              value: "8080"
          volumeMounts:
            - name: file-system
              mountPath: /files
  volumeClaimTemplates:
    - spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      metadata:
        name: file-system
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: filer-ingress
  namespace: file-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - files.keithm.io
      secretName: files-cert
  rules:
    - host: files.keithm.io
      http:
        paths:
          - backend:
              serviceName: file-server
              servicePort: 8080
---
